security:
  ignored: /open,/sdoc.jsp,/*.js,/api-docs,/api-docs/default/*,/images/*,/lib/*,/css/*,/v2/api-docs

spring.oauth2:
  resource:
    id: tap
    jwt:
      keyUri: ${sso.tokenKey}

logging:
  level:
    org.springframework.security: DEBUG
    org.trustedanalytics.uploader: DEBUG

cf:
  resource: ${sso.apiEndpoint}
  uaa: ${sso.uaaUri}

services:
  dataacquisition.url: "${data.acquisition.uri:http://localhost:9997}"
  user-management.url: ${user.management.uri:http://localhost:9998}

endpoints.enabled: false
endpoints.health.enabled: true

hdfs:
  configDir: /etc/hadoop/
  uri: "hdfs://nameservice1/tmp/%{organization}/brokers/userspace/efeedfce-05f5-4600-95f8-efd1f6c480f4/"
kerberos:
  kdc: kdc.host.addr
  realm: KDC_REALM_NAME
  user: cf
  pass: haselko
